// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newForesightManagement.proto

package grpc.newForesightManagement;

public final class NewForesightManagementImpl {
  private NewForesightManagementImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034newForesightManagement.proto\"%\n\016contai" +
      "nsString\022\023\n\013firstString\030\001 \001(\t\"\037\n\013newResp" +
      "onse\022\020\n\010firstInt\030\001 \001(\0052~\n\026newForesightMa" +
      "nagement\0224\n\016GetFirstString\022\017.containsStr" +
      "ing\032\017.containsString\"\000\022.\n\013GetFirstInt\022\017." +
      "containsString\032\014.newResponse\"\000B;\n\033grpc.n" +
      "ewForesightManagementB\032NewForesightManag" +
      "ementImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_containsString_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_containsString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsString_descriptor,
        new java.lang.String[] { "FirstString", });
    internal_static_newResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_newResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newResponse_descriptor,
        new java.lang.String[] { "FirstInt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
