// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newForesightManagement.proto

package grpc.newForesightManagement;

public interface requestCo2LevelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:requestCo2Level)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstString = 1;</code>
   */
  java.lang.String getFirstString();
  /**
   * <code>string firstString = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstStringBytes();
}
