// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newForesightManagement.proto

package grpc.newForesightManagement;

public interface responseCo2LevelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:responseCo2Level)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 first32 = 1;</code>
   */
  int getFirst32();
}
