// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newCapacityManagement.proto

package grpc.newCapacityManagement;

public final class NewCapacityManagementImpl {
  private NewCapacityManagementImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033newCapacityManagement.proto\"%\n\016contain" +
      "sString\022\023\n\013firstString\030\001 \001(\t2\301\001\n\025newCapa" +
      "cityManagement\0221\n\013GetIdAccess\022\017.contains" +
      "String\032\017.containsString\"\000\0227\n\017SendCountPe" +
      "ople\022\017.containsString\032\017.containsString\"\000" +
      "(\001\022<\n\024SendTerminalOccupied\022\017.containsStr" +
      "ing\032\017.containsString\"\000(\001B9\n\032grpc.newCapa" +
      "cityManagementB\031NewCapacityManagementImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_containsString_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_containsString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsString_descriptor,
        new java.lang.String[] { "FirstString", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
