// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newCapacityManagement.proto

package grpc.newCapacityManagement;

public interface requestIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:requestId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstString = 1;</code>
   */
  java.lang.String getFirstString();
  /**
   * <code>string firstString = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstStringBytes();
}
