// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newCapacityManagement.proto

package grpc.newCapacityManagement;

public interface responseOccupiedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:responseOccupied)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 firstInt = 1;</code>
   */
  int getFirstInt();
}
