// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package grpc.energyEfficiency;

public interface ActivateLightsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energyEfficiency.ActivateLightsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool lights_on = 1;</code>
   */
  boolean getLightsOn();
}
