// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package grpc.energyEfficiency;

public interface ActivateLightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energyEfficiency.ActivateLightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool lights_returned = 1;</code>
   */
  boolean getLightsReturned();
}
