// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package grpc.energyEfficiency;

public final class energyEfficiencyImpl {
  private energyEfficiencyImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energyEfficiency_ActivateLightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energyEfficiency_ActivateLightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energyEfficiency_ActivateLightsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energyEfficiency_ActivateLightsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energyEfficiency_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energyEfficiency_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energyEfficiency_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energyEfficiency_TemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energyEfficiency_PresRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energyEfficiency_PresRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energyEfficiency_PresRoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energyEfficiency_PresRoomResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energyEfficiency_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energyEfficiency_ErrorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026energyEfficiency.proto\022\020energyEfficien" +
      "cy\"*\n\025ActivateLightsRequest\022\021\n\tlights_on" +
      "\030\001 \001(\010\"1\n\026ActivateLightsResponse\022\027\n\017ligh" +
      "ts_returned\030\001 \001(\010\"\'\n\022TemperatureRequest\022" +
      "\021\n\twhat_temp\030\001 \001(\005\"*\n\023TemperatureRespons" +
      "e\022\023\n\013return_temp\030\001 \001(\005\"8\n\017PresRoomReques" +
      "t\022%\n\035ActivatePresRoomBlindsRequest\030\001 \001(\010" +
      "\":\n\020PresRoomResponse\022&\n\036ActivatePresRoom" +
      "BlindsResponse\030\001 \001(\010\"O\n\rErrorResponse\022\r\n" +
      "\005input\030\001 \001(\005\022/\n\nerror_code\030\002 \001(\0162\033.energ" +
      "yEfficiency.ErrorCode*\'\n\tErrorCode\022\r\n\tAB" +
      "OVE_100\020\000\022\013\n\007BELOW_1\020\0012\267\002\n\020energyEfficie" +
      "ncy\022g\n\016ActivateLights\022\'.energyEfficiency" +
      ".ActivateLightsRequest\032(.energyEfficienc" +
      "y.ActivateLightsResponse\"\0000\001\022c\n\020CheckTem" +
      "perature\022$.energyEfficiency.TemperatureR" +
      "equest\032%.energyEfficiency.TemperatureRes" +
      "ponse\"\0000\001\022U\n\010PresRoom\022!.energyEfficiency" +
      ".PresRoomRequest\032\".energyEfficiency.Pres" +
      "RoomResponse\"\0000\001B/\n\025grpc.energyEfficienc" +
      "yB\024energyEfficiencyImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_energyEfficiency_ActivateLightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_energyEfficiency_ActivateLightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energyEfficiency_ActivateLightsRequest_descriptor,
        new java.lang.String[] { "LightsOn", });
    internal_static_energyEfficiency_ActivateLightsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_energyEfficiency_ActivateLightsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energyEfficiency_ActivateLightsResponse_descriptor,
        new java.lang.String[] { "LightsReturned", });
    internal_static_energyEfficiency_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_energyEfficiency_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energyEfficiency_TemperatureRequest_descriptor,
        new java.lang.String[] { "WhatTemp", });
    internal_static_energyEfficiency_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_energyEfficiency_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energyEfficiency_TemperatureResponse_descriptor,
        new java.lang.String[] { "ReturnTemp", });
    internal_static_energyEfficiency_PresRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_energyEfficiency_PresRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energyEfficiency_PresRoomRequest_descriptor,
        new java.lang.String[] { "ActivatePresRoomBlindsRequest", });
    internal_static_energyEfficiency_PresRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_energyEfficiency_PresRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energyEfficiency_PresRoomResponse_descriptor,
        new java.lang.String[] { "ActivatePresRoomBlindsResponse", });
    internal_static_energyEfficiency_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_energyEfficiency_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energyEfficiency_ErrorResponse_descriptor,
        new java.lang.String[] { "Input", "ErrorCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
