// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package grpc.energyEfficiency;

public interface ErrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energyEfficiency.ErrorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 input = 1;</code>
   */
  int getInput();

  /**
   * <code>.energyEfficiency.ErrorCode error_code = 2;</code>
   */
  int getErrorCodeValue();
  /**
   * <code>.energyEfficiency.ErrorCode error_code = 2;</code>
   */
  grpc.energyEfficiency.ErrorCode getErrorCode();
}
