// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package grpc.energyEfficiency;

public interface PresRoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energyEfficiency.PresRoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ActivatePresRoomBlindsResponse = 1;</code>
   */
  boolean getActivatePresRoomBlindsResponse();
}
