// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package grpc.energyEfficiency;

public interface PresRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energyEfficiency.PresRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ActivatePresRoomBlindsRequest = 1;</code>
   */
  boolean getActivatePresRoomBlindsRequest();
}
