// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package grpc.energyEfficiency;

/**
 * <pre>
 * message request for PresRoom
 * </pre>
 *
 * Protobuf type {@code energyEfficiency.PresRoomRequest}
 */
public  final class PresRoomRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:energyEfficiency.PresRoomRequest)
    PresRoomRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PresRoomRequest.newBuilder() to construct.
  private PresRoomRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PresRoomRequest() {
    activatePresRoomBlindsRequest_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PresRoomRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            activatePresRoomBlindsRequest_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.energyEfficiency.energyEfficiencyImpl.internal_static_energyEfficiency_PresRoomRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.energyEfficiency.energyEfficiencyImpl.internal_static_energyEfficiency_PresRoomRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.energyEfficiency.PresRoomRequest.class, grpc.energyEfficiency.PresRoomRequest.Builder.class);
  }

  public static final int ACTIVATEPRESROOMBLINDSREQUEST_FIELD_NUMBER = 1;
  private boolean activatePresRoomBlindsRequest_;
  /**
   * <code>bool ActivatePresRoomBlindsRequest = 1;</code>
   */
  public boolean getActivatePresRoomBlindsRequest() {
    return activatePresRoomBlindsRequest_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (activatePresRoomBlindsRequest_ != false) {
      output.writeBool(1, activatePresRoomBlindsRequest_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (activatePresRoomBlindsRequest_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, activatePresRoomBlindsRequest_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.energyEfficiency.PresRoomRequest)) {
      return super.equals(obj);
    }
    grpc.energyEfficiency.PresRoomRequest other = (grpc.energyEfficiency.PresRoomRequest) obj;

    boolean result = true;
    result = result && (getActivatePresRoomBlindsRequest()
        == other.getActivatePresRoomBlindsRequest());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTIVATEPRESROOMBLINDSREQUEST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getActivatePresRoomBlindsRequest());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.energyEfficiency.PresRoomRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.energyEfficiency.PresRoomRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.energyEfficiency.PresRoomRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.energyEfficiency.PresRoomRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.energyEfficiency.PresRoomRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.energyEfficiency.PresRoomRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.energyEfficiency.PresRoomRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.energyEfficiency.PresRoomRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.energyEfficiency.PresRoomRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.energyEfficiency.PresRoomRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.energyEfficiency.PresRoomRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.energyEfficiency.PresRoomRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.energyEfficiency.PresRoomRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * message request for PresRoom
   * </pre>
   *
   * Protobuf type {@code energyEfficiency.PresRoomRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:energyEfficiency.PresRoomRequest)
      grpc.energyEfficiency.PresRoomRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.energyEfficiency.energyEfficiencyImpl.internal_static_energyEfficiency_PresRoomRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.energyEfficiency.energyEfficiencyImpl.internal_static_energyEfficiency_PresRoomRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.energyEfficiency.PresRoomRequest.class, grpc.energyEfficiency.PresRoomRequest.Builder.class);
    }

    // Construct using grpc.energyEfficiency.PresRoomRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      activatePresRoomBlindsRequest_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.energyEfficiency.energyEfficiencyImpl.internal_static_energyEfficiency_PresRoomRequest_descriptor;
    }

    @java.lang.Override
    public grpc.energyEfficiency.PresRoomRequest getDefaultInstanceForType() {
      return grpc.energyEfficiency.PresRoomRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.energyEfficiency.PresRoomRequest build() {
      grpc.energyEfficiency.PresRoomRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.energyEfficiency.PresRoomRequest buildPartial() {
      grpc.energyEfficiency.PresRoomRequest result = new grpc.energyEfficiency.PresRoomRequest(this);
      result.activatePresRoomBlindsRequest_ = activatePresRoomBlindsRequest_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.energyEfficiency.PresRoomRequest) {
        return mergeFrom((grpc.energyEfficiency.PresRoomRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.energyEfficiency.PresRoomRequest other) {
      if (other == grpc.energyEfficiency.PresRoomRequest.getDefaultInstance()) return this;
      if (other.getActivatePresRoomBlindsRequest() != false) {
        setActivatePresRoomBlindsRequest(other.getActivatePresRoomBlindsRequest());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.energyEfficiency.PresRoomRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.energyEfficiency.PresRoomRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean activatePresRoomBlindsRequest_ ;
    /**
     * <code>bool ActivatePresRoomBlindsRequest = 1;</code>
     */
    public boolean getActivatePresRoomBlindsRequest() {
      return activatePresRoomBlindsRequest_;
    }
    /**
     * <code>bool ActivatePresRoomBlindsRequest = 1;</code>
     */
    public Builder setActivatePresRoomBlindsRequest(boolean value) {
      
      activatePresRoomBlindsRequest_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool ActivatePresRoomBlindsRequest = 1;</code>
     */
    public Builder clearActivatePresRoomBlindsRequest() {
      
      activatePresRoomBlindsRequest_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:energyEfficiency.PresRoomRequest)
  }

  // @@protoc_insertion_point(class_scope:energyEfficiency.PresRoomRequest)
  private static final grpc.energyEfficiency.PresRoomRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.energyEfficiency.PresRoomRequest();
  }

  public static grpc.energyEfficiency.PresRoomRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PresRoomRequest>
      PARSER = new com.google.protobuf.AbstractParser<PresRoomRequest>() {
    @java.lang.Override
    public PresRoomRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PresRoomRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PresRoomRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PresRoomRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.energyEfficiency.PresRoomRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

