// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package grpc.energyEfficiency;

public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energyEfficiency.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 what_temp = 1;</code>
   */
  int getWhatTemp();
}
