// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package grpc.energyEfficiency;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energyEfficiency.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 return_temp = 1;</code>
   */
  int getReturnTemp();
}
