// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacityManagement.proto

package grpc.capacityManagement;

public final class capacityManagementImpl {
  private capacityManagementImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capacityManagement_IdAccessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_capacityManagement_IdAccessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capacityManagement_IdAccessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_capacityManagement_IdAccessResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capacityManagement_UpdateCountPeopleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_capacityManagement_UpdateCountPeopleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capacityManagement_UpdateCountPeopleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_capacityManagement_UpdateCountPeopleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capacityManagement_TerminalOccupiedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_capacityManagement_TerminalOccupiedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capacityManagement_TerminalOccupiedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_capacityManagement_TerminalOccupiedResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030capacityManagement.proto\022\022capacityMana" +
      "gement\"\'\n\017IdAccessRequest\022\024\n\014Id_availabl" +
      "e\030\001 \001(\010\"(\n\020IdAccessResponse\022\024\n\014Id_availa" +
      "ble\030\001 \001(\010\"0\n\030UpdateCountPeopleRequest\022\024\n" +
      "\014count_people\030\001 \001(\005\"3\n\031UpdateCountPeople" +
      "Response\022\026\n\016counted_people\030\001 \001(\005\"5\n\027Term" +
      "inalOccupiedRequest\022\032\n\022terminal_availabl" +
      "e\030\001 \001(\010\"0\n\030TerminalOccupiedResponse\022\024\n\014n" +
      "o_available\030\001 \001(\0102\330\002\n\022capacityManagement" +
      "\022]\n\016CreateIdAccess\022#.capacityManagement." +
      "IdAccessRequest\032$.capacityManagement.IdA" +
      "ccessResponse\"\000\022n\n\rCSCountPeople\022,.capac" +
      "ityManagement.UpdateCountPeopleRequest\032-" +
      ".capacityManagement.UpdateCountPeopleRes" +
      "ponse\"\000\022s\n\022CSTerminalOccupied\022+.capacity" +
      "Management.TerminalOccupiedRequest\032,.cap" +
      "acityManagement.TerminalOccupiedResponse" +
      "\"\000(\001B3\n\027grpc.capacityManagementB\026capacit" +
      "yManagementImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_capacityManagement_IdAccessRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_capacityManagement_IdAccessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_capacityManagement_IdAccessRequest_descriptor,
        new java.lang.String[] { "IdAvailable", });
    internal_static_capacityManagement_IdAccessResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_capacityManagement_IdAccessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_capacityManagement_IdAccessResponse_descriptor,
        new java.lang.String[] { "IdAvailable", });
    internal_static_capacityManagement_UpdateCountPeopleRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_capacityManagement_UpdateCountPeopleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_capacityManagement_UpdateCountPeopleRequest_descriptor,
        new java.lang.String[] { "CountPeople", });
    internal_static_capacityManagement_UpdateCountPeopleResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_capacityManagement_UpdateCountPeopleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_capacityManagement_UpdateCountPeopleResponse_descriptor,
        new java.lang.String[] { "CountedPeople", });
    internal_static_capacityManagement_TerminalOccupiedRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_capacityManagement_TerminalOccupiedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_capacityManagement_TerminalOccupiedRequest_descriptor,
        new java.lang.String[] { "TerminalAvailable", });
    internal_static_capacityManagement_TerminalOccupiedResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_capacityManagement_TerminalOccupiedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_capacityManagement_TerminalOccupiedResponse_descriptor,
        new java.lang.String[] { "NoAvailable", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
