// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacityManagement.proto

package grpc.capacityManagement;

public interface IdAccessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:capacityManagement.IdAccessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool Id_available = 1;</code>
   */
  boolean getIdAvailable();
}
