// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacityManagement.proto

package grpc.capacityManagement;

public interface IdAccessResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:capacityManagement.IdAccessResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool Id_available = 1;</code>
   */
  boolean getIdAvailable();
}
