// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacityManagement.proto

package grpc.capacityManagement;

/**
 * <pre>
 * message response for CSTerminalOccupied
 * </pre>
 *
 * Protobuf type {@code capacityManagement.TerminalOccupiedResponse}
 */
public  final class TerminalOccupiedResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:capacityManagement.TerminalOccupiedResponse)
    TerminalOccupiedResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TerminalOccupiedResponse.newBuilder() to construct.
  private TerminalOccupiedResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TerminalOccupiedResponse() {
    noAvailable_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TerminalOccupiedResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            noAvailable_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.capacityManagement.capacityManagementImpl.internal_static_capacityManagement_TerminalOccupiedResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.capacityManagement.capacityManagementImpl.internal_static_capacityManagement_TerminalOccupiedResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.capacityManagement.TerminalOccupiedResponse.class, grpc.capacityManagement.TerminalOccupiedResponse.Builder.class);
  }

  public static final int NO_AVAILABLE_FIELD_NUMBER = 1;
  private boolean noAvailable_;
  /**
   * <code>bool no_available = 1;</code>
   */
  public boolean getNoAvailable() {
    return noAvailable_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (noAvailable_ != false) {
      output.writeBool(1, noAvailable_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (noAvailable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, noAvailable_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.capacityManagement.TerminalOccupiedResponse)) {
      return super.equals(obj);
    }
    grpc.capacityManagement.TerminalOccupiedResponse other = (grpc.capacityManagement.TerminalOccupiedResponse) obj;

    boolean result = true;
    result = result && (getNoAvailable()
        == other.getNoAvailable());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NO_AVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNoAvailable());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.capacityManagement.TerminalOccupiedResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.capacityManagement.TerminalOccupiedResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.capacityManagement.TerminalOccupiedResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.capacityManagement.TerminalOccupiedResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.capacityManagement.TerminalOccupiedResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.capacityManagement.TerminalOccupiedResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.capacityManagement.TerminalOccupiedResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.capacityManagement.TerminalOccupiedResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.capacityManagement.TerminalOccupiedResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.capacityManagement.TerminalOccupiedResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.capacityManagement.TerminalOccupiedResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.capacityManagement.TerminalOccupiedResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.capacityManagement.TerminalOccupiedResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * message response for CSTerminalOccupied
   * </pre>
   *
   * Protobuf type {@code capacityManagement.TerminalOccupiedResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:capacityManagement.TerminalOccupiedResponse)
      grpc.capacityManagement.TerminalOccupiedResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.capacityManagement.capacityManagementImpl.internal_static_capacityManagement_TerminalOccupiedResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.capacityManagement.capacityManagementImpl.internal_static_capacityManagement_TerminalOccupiedResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.capacityManagement.TerminalOccupiedResponse.class, grpc.capacityManagement.TerminalOccupiedResponse.Builder.class);
    }

    // Construct using grpc.capacityManagement.TerminalOccupiedResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      noAvailable_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.capacityManagement.capacityManagementImpl.internal_static_capacityManagement_TerminalOccupiedResponse_descriptor;
    }

    @java.lang.Override
    public grpc.capacityManagement.TerminalOccupiedResponse getDefaultInstanceForType() {
      return grpc.capacityManagement.TerminalOccupiedResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.capacityManagement.TerminalOccupiedResponse build() {
      grpc.capacityManagement.TerminalOccupiedResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.capacityManagement.TerminalOccupiedResponse buildPartial() {
      grpc.capacityManagement.TerminalOccupiedResponse result = new grpc.capacityManagement.TerminalOccupiedResponse(this);
      result.noAvailable_ = noAvailable_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.capacityManagement.TerminalOccupiedResponse) {
        return mergeFrom((grpc.capacityManagement.TerminalOccupiedResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.capacityManagement.TerminalOccupiedResponse other) {
      if (other == grpc.capacityManagement.TerminalOccupiedResponse.getDefaultInstance()) return this;
      if (other.getNoAvailable() != false) {
        setNoAvailable(other.getNoAvailable());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.capacityManagement.TerminalOccupiedResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.capacityManagement.TerminalOccupiedResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean noAvailable_ ;
    /**
     * <code>bool no_available = 1;</code>
     */
    public boolean getNoAvailable() {
      return noAvailable_;
    }
    /**
     * <code>bool no_available = 1;</code>
     */
    public Builder setNoAvailable(boolean value) {
      
      noAvailable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool no_available = 1;</code>
     */
    public Builder clearNoAvailable() {
      
      noAvailable_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:capacityManagement.TerminalOccupiedResponse)
  }

  // @@protoc_insertion_point(class_scope:capacityManagement.TerminalOccupiedResponse)
  private static final grpc.capacityManagement.TerminalOccupiedResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.capacityManagement.TerminalOccupiedResponse();
  }

  public static grpc.capacityManagement.TerminalOccupiedResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TerminalOccupiedResponse>
      PARSER = new com.google.protobuf.AbstractParser<TerminalOccupiedResponse>() {
    @java.lang.Override
    public TerminalOccupiedResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TerminalOccupiedResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TerminalOccupiedResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TerminalOccupiedResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.capacityManagement.TerminalOccupiedResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

