// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacityManagement.proto

package grpc.capacityManagement;

public interface TerminalOccupiedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:capacityManagement.TerminalOccupiedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool no_available = 1;</code>
   */
  boolean getNoAvailable();
}
