// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacityManagement.proto

package grpc.capacityManagement;

public interface TerminalOccupiedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:capacityManagement.TerminalOccupiedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool terminal_available = 1;</code>
   */
  boolean getTerminalAvailable();
}
