// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacityManagement.proto

package grpc.capacityManagement;

public interface UpdateCountPeopleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:capacityManagement.UpdateCountPeopleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 counted_people = 1;</code>
   */
  int getCountedPeople();
}
