// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacityManagement.proto

package grpc.capacityManagement;

public interface UpdateCountPeopleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:capacityManagement.UpdateCountPeopleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count_people = 1;</code>
   */
  int getCountPeople();
}
