// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foresightMaintenance.proto

package grpc.foresightMaintenance;

public interface CheckElecUsageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foresightMaintenance.CheckElecUsageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 elec_usage_room1 = 1;</code>
   */
  int getElecUsageRoom1();

  /**
   * <code>int32 elec_usage_room2 = 2;</code>
   */
  int getElecUsageRoom2();

  /**
   * <code>int32 elec_usage_room3 = 3;</code>
   */
  int getElecUsageRoom3();
}
