// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foresightMaintenance.proto

package grpc.foresightMaintenance;

/**
 * <pre>
 * message request for CheckDecibelLevels
 * </pre>
 *
 * Protobuf type {@code foresightMaintenance.CheckDecibelLevelsRequest}
 */
public  final class CheckDecibelLevelsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:foresightMaintenance.CheckDecibelLevelsRequest)
    CheckDecibelLevelsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckDecibelLevelsRequest.newBuilder() to construct.
  private CheckDecibelLevelsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckDecibelLevelsRequest() {
    decibelRoom1_ = 0;
    decibelRoom2_ = 0;
    decibelRoom3_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CheckDecibelLevelsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            decibelRoom1_ = input.readInt32();
            break;
          }
          case 16: {

            decibelRoom2_ = input.readInt32();
            break;
          }
          case 24: {

            decibelRoom3_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckDecibelLevelsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckDecibelLevelsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.foresightMaintenance.CheckDecibelLevelsRequest.class, grpc.foresightMaintenance.CheckDecibelLevelsRequest.Builder.class);
  }

  public static final int DECIBEL_ROOM1_FIELD_NUMBER = 1;
  private int decibelRoom1_;
  /**
   * <code>int32 decibel_room1 = 1;</code>
   */
  public int getDecibelRoom1() {
    return decibelRoom1_;
  }

  public static final int DECIBEL_ROOM2_FIELD_NUMBER = 2;
  private int decibelRoom2_;
  /**
   * <code>int32 decibel_room2 = 2;</code>
   */
  public int getDecibelRoom2() {
    return decibelRoom2_;
  }

  public static final int DECIBEL_ROOM3_FIELD_NUMBER = 3;
  private int decibelRoom3_;
  /**
   * <code>int32 decibel_room3 = 3;</code>
   */
  public int getDecibelRoom3() {
    return decibelRoom3_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (decibelRoom1_ != 0) {
      output.writeInt32(1, decibelRoom1_);
    }
    if (decibelRoom2_ != 0) {
      output.writeInt32(2, decibelRoom2_);
    }
    if (decibelRoom3_ != 0) {
      output.writeInt32(3, decibelRoom3_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (decibelRoom1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, decibelRoom1_);
    }
    if (decibelRoom2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, decibelRoom2_);
    }
    if (decibelRoom3_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, decibelRoom3_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.foresightMaintenance.CheckDecibelLevelsRequest)) {
      return super.equals(obj);
    }
    grpc.foresightMaintenance.CheckDecibelLevelsRequest other = (grpc.foresightMaintenance.CheckDecibelLevelsRequest) obj;

    boolean result = true;
    result = result && (getDecibelRoom1()
        == other.getDecibelRoom1());
    result = result && (getDecibelRoom2()
        == other.getDecibelRoom2());
    result = result && (getDecibelRoom3()
        == other.getDecibelRoom3());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DECIBEL_ROOM1_FIELD_NUMBER;
    hash = (53 * hash) + getDecibelRoom1();
    hash = (37 * hash) + DECIBEL_ROOM2_FIELD_NUMBER;
    hash = (53 * hash) + getDecibelRoom2();
    hash = (37 * hash) + DECIBEL_ROOM3_FIELD_NUMBER;
    hash = (53 * hash) + getDecibelRoom3();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.foresightMaintenance.CheckDecibelLevelsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foresightMaintenance.CheckDecibelLevelsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckDecibelLevelsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foresightMaintenance.CheckDecibelLevelsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckDecibelLevelsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foresightMaintenance.CheckDecibelLevelsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckDecibelLevelsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foresightMaintenance.CheckDecibelLevelsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckDecibelLevelsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.foresightMaintenance.CheckDecibelLevelsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckDecibelLevelsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foresightMaintenance.CheckDecibelLevelsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.foresightMaintenance.CheckDecibelLevelsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * message request for CheckDecibelLevels
   * </pre>
   *
   * Protobuf type {@code foresightMaintenance.CheckDecibelLevelsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:foresightMaintenance.CheckDecibelLevelsRequest)
      grpc.foresightMaintenance.CheckDecibelLevelsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckDecibelLevelsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckDecibelLevelsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.foresightMaintenance.CheckDecibelLevelsRequest.class, grpc.foresightMaintenance.CheckDecibelLevelsRequest.Builder.class);
    }

    // Construct using grpc.foresightMaintenance.CheckDecibelLevelsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      decibelRoom1_ = 0;

      decibelRoom2_ = 0;

      decibelRoom3_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckDecibelLevelsRequest_descriptor;
    }

    @java.lang.Override
    public grpc.foresightMaintenance.CheckDecibelLevelsRequest getDefaultInstanceForType() {
      return grpc.foresightMaintenance.CheckDecibelLevelsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.foresightMaintenance.CheckDecibelLevelsRequest build() {
      grpc.foresightMaintenance.CheckDecibelLevelsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.foresightMaintenance.CheckDecibelLevelsRequest buildPartial() {
      grpc.foresightMaintenance.CheckDecibelLevelsRequest result = new grpc.foresightMaintenance.CheckDecibelLevelsRequest(this);
      result.decibelRoom1_ = decibelRoom1_;
      result.decibelRoom2_ = decibelRoom2_;
      result.decibelRoom3_ = decibelRoom3_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.foresightMaintenance.CheckDecibelLevelsRequest) {
        return mergeFrom((grpc.foresightMaintenance.CheckDecibelLevelsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.foresightMaintenance.CheckDecibelLevelsRequest other) {
      if (other == grpc.foresightMaintenance.CheckDecibelLevelsRequest.getDefaultInstance()) return this;
      if (other.getDecibelRoom1() != 0) {
        setDecibelRoom1(other.getDecibelRoom1());
      }
      if (other.getDecibelRoom2() != 0) {
        setDecibelRoom2(other.getDecibelRoom2());
      }
      if (other.getDecibelRoom3() != 0) {
        setDecibelRoom3(other.getDecibelRoom3());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.foresightMaintenance.CheckDecibelLevelsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.foresightMaintenance.CheckDecibelLevelsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int decibelRoom1_ ;
    /**
     * <code>int32 decibel_room1 = 1;</code>
     */
    public int getDecibelRoom1() {
      return decibelRoom1_;
    }
    /**
     * <code>int32 decibel_room1 = 1;</code>
     */
    public Builder setDecibelRoom1(int value) {
      
      decibelRoom1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 decibel_room1 = 1;</code>
     */
    public Builder clearDecibelRoom1() {
      
      decibelRoom1_ = 0;
      onChanged();
      return this;
    }

    private int decibelRoom2_ ;
    /**
     * <code>int32 decibel_room2 = 2;</code>
     */
    public int getDecibelRoom2() {
      return decibelRoom2_;
    }
    /**
     * <code>int32 decibel_room2 = 2;</code>
     */
    public Builder setDecibelRoom2(int value) {
      
      decibelRoom2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 decibel_room2 = 2;</code>
     */
    public Builder clearDecibelRoom2() {
      
      decibelRoom2_ = 0;
      onChanged();
      return this;
    }

    private int decibelRoom3_ ;
    /**
     * <code>int32 decibel_room3 = 3;</code>
     */
    public int getDecibelRoom3() {
      return decibelRoom3_;
    }
    /**
     * <code>int32 decibel_room3 = 3;</code>
     */
    public Builder setDecibelRoom3(int value) {
      
      decibelRoom3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 decibel_room3 = 3;</code>
     */
    public Builder clearDecibelRoom3() {
      
      decibelRoom3_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:foresightMaintenance.CheckDecibelLevelsRequest)
  }

  // @@protoc_insertion_point(class_scope:foresightMaintenance.CheckDecibelLevelsRequest)
  private static final grpc.foresightMaintenance.CheckDecibelLevelsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.foresightMaintenance.CheckDecibelLevelsRequest();
  }

  public static grpc.foresightMaintenance.CheckDecibelLevelsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckDecibelLevelsRequest>
      PARSER = new com.google.protobuf.AbstractParser<CheckDecibelLevelsRequest>() {
    @java.lang.Override
    public CheckDecibelLevelsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CheckDecibelLevelsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CheckDecibelLevelsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckDecibelLevelsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.foresightMaintenance.CheckDecibelLevelsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

