// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foresightMaintenance.proto

package grpc.foresightMaintenance;

/**
 * <pre>
 * message request for CheckCo2Levels
 * </pre>
 *
 * Protobuf type {@code foresightMaintenance.CheckCo2LevelsRequest}
 */
public  final class CheckCo2LevelsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:foresightMaintenance.CheckCo2LevelsRequest)
    CheckCo2LevelsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckCo2LevelsRequest.newBuilder() to construct.
  private CheckCo2LevelsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckCo2LevelsRequest() {
    co2LevelRoom1_ = 0;
    co2LevelRoom2_ = 0;
    co2LevelRoom3_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CheckCo2LevelsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            co2LevelRoom1_ = input.readInt32();
            break;
          }
          case 16: {

            co2LevelRoom2_ = input.readInt32();
            break;
          }
          case 24: {

            co2LevelRoom3_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckCo2LevelsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckCo2LevelsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.foresightMaintenance.CheckCo2LevelsRequest.class, grpc.foresightMaintenance.CheckCo2LevelsRequest.Builder.class);
  }

  public static final int CO2LEVEL_ROOM1_FIELD_NUMBER = 1;
  private int co2LevelRoom1_;
  /**
   * <code>int32 co2level_room1 = 1;</code>
   */
  public int getCo2LevelRoom1() {
    return co2LevelRoom1_;
  }

  public static final int CO2LEVEL_ROOM2_FIELD_NUMBER = 2;
  private int co2LevelRoom2_;
  /**
   * <code>int32 co2level_room2 = 2;</code>
   */
  public int getCo2LevelRoom2() {
    return co2LevelRoom2_;
  }

  public static final int CO2LEVEL_ROOM3_FIELD_NUMBER = 3;
  private int co2LevelRoom3_;
  /**
   * <code>int32 co2level_room3 = 3;</code>
   */
  public int getCo2LevelRoom3() {
    return co2LevelRoom3_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (co2LevelRoom1_ != 0) {
      output.writeInt32(1, co2LevelRoom1_);
    }
    if (co2LevelRoom2_ != 0) {
      output.writeInt32(2, co2LevelRoom2_);
    }
    if (co2LevelRoom3_ != 0) {
      output.writeInt32(3, co2LevelRoom3_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (co2LevelRoom1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, co2LevelRoom1_);
    }
    if (co2LevelRoom2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, co2LevelRoom2_);
    }
    if (co2LevelRoom3_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, co2LevelRoom3_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.foresightMaintenance.CheckCo2LevelsRequest)) {
      return super.equals(obj);
    }
    grpc.foresightMaintenance.CheckCo2LevelsRequest other = (grpc.foresightMaintenance.CheckCo2LevelsRequest) obj;

    boolean result = true;
    result = result && (getCo2LevelRoom1()
        == other.getCo2LevelRoom1());
    result = result && (getCo2LevelRoom2()
        == other.getCo2LevelRoom2());
    result = result && (getCo2LevelRoom3()
        == other.getCo2LevelRoom3());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CO2LEVEL_ROOM1_FIELD_NUMBER;
    hash = (53 * hash) + getCo2LevelRoom1();
    hash = (37 * hash) + CO2LEVEL_ROOM2_FIELD_NUMBER;
    hash = (53 * hash) + getCo2LevelRoom2();
    hash = (37 * hash) + CO2LEVEL_ROOM3_FIELD_NUMBER;
    hash = (53 * hash) + getCo2LevelRoom3();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.foresightMaintenance.CheckCo2LevelsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foresightMaintenance.CheckCo2LevelsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckCo2LevelsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foresightMaintenance.CheckCo2LevelsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckCo2LevelsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foresightMaintenance.CheckCo2LevelsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckCo2LevelsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foresightMaintenance.CheckCo2LevelsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckCo2LevelsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.foresightMaintenance.CheckCo2LevelsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckCo2LevelsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foresightMaintenance.CheckCo2LevelsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.foresightMaintenance.CheckCo2LevelsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * message request for CheckCo2Levels
   * </pre>
   *
   * Protobuf type {@code foresightMaintenance.CheckCo2LevelsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:foresightMaintenance.CheckCo2LevelsRequest)
      grpc.foresightMaintenance.CheckCo2LevelsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckCo2LevelsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckCo2LevelsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.foresightMaintenance.CheckCo2LevelsRequest.class, grpc.foresightMaintenance.CheckCo2LevelsRequest.Builder.class);
    }

    // Construct using grpc.foresightMaintenance.CheckCo2LevelsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      co2LevelRoom1_ = 0;

      co2LevelRoom2_ = 0;

      co2LevelRoom3_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckCo2LevelsRequest_descriptor;
    }

    @java.lang.Override
    public grpc.foresightMaintenance.CheckCo2LevelsRequest getDefaultInstanceForType() {
      return grpc.foresightMaintenance.CheckCo2LevelsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.foresightMaintenance.CheckCo2LevelsRequest build() {
      grpc.foresightMaintenance.CheckCo2LevelsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.foresightMaintenance.CheckCo2LevelsRequest buildPartial() {
      grpc.foresightMaintenance.CheckCo2LevelsRequest result = new grpc.foresightMaintenance.CheckCo2LevelsRequest(this);
      result.co2LevelRoom1_ = co2LevelRoom1_;
      result.co2LevelRoom2_ = co2LevelRoom2_;
      result.co2LevelRoom3_ = co2LevelRoom3_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.foresightMaintenance.CheckCo2LevelsRequest) {
        return mergeFrom((grpc.foresightMaintenance.CheckCo2LevelsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.foresightMaintenance.CheckCo2LevelsRequest other) {
      if (other == grpc.foresightMaintenance.CheckCo2LevelsRequest.getDefaultInstance()) return this;
      if (other.getCo2LevelRoom1() != 0) {
        setCo2LevelRoom1(other.getCo2LevelRoom1());
      }
      if (other.getCo2LevelRoom2() != 0) {
        setCo2LevelRoom2(other.getCo2LevelRoom2());
      }
      if (other.getCo2LevelRoom3() != 0) {
        setCo2LevelRoom3(other.getCo2LevelRoom3());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.foresightMaintenance.CheckCo2LevelsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.foresightMaintenance.CheckCo2LevelsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int co2LevelRoom1_ ;
    /**
     * <code>int32 co2level_room1 = 1;</code>
     */
    public int getCo2LevelRoom1() {
      return co2LevelRoom1_;
    }
    /**
     * <code>int32 co2level_room1 = 1;</code>
     */
    public Builder setCo2LevelRoom1(int value) {
      
      co2LevelRoom1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 co2level_room1 = 1;</code>
     */
    public Builder clearCo2LevelRoom1() {
      
      co2LevelRoom1_ = 0;
      onChanged();
      return this;
    }

    private int co2LevelRoom2_ ;
    /**
     * <code>int32 co2level_room2 = 2;</code>
     */
    public int getCo2LevelRoom2() {
      return co2LevelRoom2_;
    }
    /**
     * <code>int32 co2level_room2 = 2;</code>
     */
    public Builder setCo2LevelRoom2(int value) {
      
      co2LevelRoom2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 co2level_room2 = 2;</code>
     */
    public Builder clearCo2LevelRoom2() {
      
      co2LevelRoom2_ = 0;
      onChanged();
      return this;
    }

    private int co2LevelRoom3_ ;
    /**
     * <code>int32 co2level_room3 = 3;</code>
     */
    public int getCo2LevelRoom3() {
      return co2LevelRoom3_;
    }
    /**
     * <code>int32 co2level_room3 = 3;</code>
     */
    public Builder setCo2LevelRoom3(int value) {
      
      co2LevelRoom3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 co2level_room3 = 3;</code>
     */
    public Builder clearCo2LevelRoom3() {
      
      co2LevelRoom3_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:foresightMaintenance.CheckCo2LevelsRequest)
  }

  // @@protoc_insertion_point(class_scope:foresightMaintenance.CheckCo2LevelsRequest)
  private static final grpc.foresightMaintenance.CheckCo2LevelsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.foresightMaintenance.CheckCo2LevelsRequest();
  }

  public static grpc.foresightMaintenance.CheckCo2LevelsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckCo2LevelsRequest>
      PARSER = new com.google.protobuf.AbstractParser<CheckCo2LevelsRequest>() {
    @java.lang.Override
    public CheckCo2LevelsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CheckCo2LevelsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CheckCo2LevelsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckCo2LevelsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.foresightMaintenance.CheckCo2LevelsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

