// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foresightMaintenance.proto

package grpc.foresightMaintenance;

public interface CheckDecibelLevelsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foresightMaintenance.CheckDecibelLevelsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 decibel_room1 = 1;</code>
   */
  int getDecibelRoom1();

  /**
   * <code>int32 decibel_room2 = 2;</code>
   */
  int getDecibelRoom2();

  /**
   * <code>int32 decibel_room3 = 3;</code>
   */
  int getDecibelRoom3();
}
