// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foresightMaintenance.proto

package grpc.foresightMaintenance;

/**
 * <pre>
 *message response for CheckElecUsage
 * </pre>
 *
 * Protobuf type {@code foresightMaintenance.CheckElecUsageResponse}
 */
public  final class CheckElecUsageResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:foresightMaintenance.CheckElecUsageResponse)
    CheckElecUsageResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckElecUsageResponse.newBuilder() to construct.
  private CheckElecUsageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckElecUsageResponse() {
    elecUsageRoom1_ = 0;
    elecUsageRoom2_ = 0;
    elecUsageRoom3_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CheckElecUsageResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            elecUsageRoom1_ = input.readInt32();
            break;
          }
          case 16: {

            elecUsageRoom2_ = input.readInt32();
            break;
          }
          case 24: {

            elecUsageRoom3_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckElecUsageResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckElecUsageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.foresightMaintenance.CheckElecUsageResponse.class, grpc.foresightMaintenance.CheckElecUsageResponse.Builder.class);
  }

  public static final int ELEC_USAGE_ROOM1_FIELD_NUMBER = 1;
  private int elecUsageRoom1_;
  /**
   * <code>int32 elec_usage_room1 = 1;</code>
   */
  public int getElecUsageRoom1() {
    return elecUsageRoom1_;
  }

  public static final int ELEC_USAGE_ROOM2_FIELD_NUMBER = 2;
  private int elecUsageRoom2_;
  /**
   * <code>int32 elec_usage_room2 = 2;</code>
   */
  public int getElecUsageRoom2() {
    return elecUsageRoom2_;
  }

  public static final int ELEC_USAGE_ROOM3_FIELD_NUMBER = 3;
  private int elecUsageRoom3_;
  /**
   * <code>int32 elec_usage_room3 = 3;</code>
   */
  public int getElecUsageRoom3() {
    return elecUsageRoom3_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (elecUsageRoom1_ != 0) {
      output.writeInt32(1, elecUsageRoom1_);
    }
    if (elecUsageRoom2_ != 0) {
      output.writeInt32(2, elecUsageRoom2_);
    }
    if (elecUsageRoom3_ != 0) {
      output.writeInt32(3, elecUsageRoom3_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (elecUsageRoom1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, elecUsageRoom1_);
    }
    if (elecUsageRoom2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, elecUsageRoom2_);
    }
    if (elecUsageRoom3_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, elecUsageRoom3_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.foresightMaintenance.CheckElecUsageResponse)) {
      return super.equals(obj);
    }
    grpc.foresightMaintenance.CheckElecUsageResponse other = (grpc.foresightMaintenance.CheckElecUsageResponse) obj;

    boolean result = true;
    result = result && (getElecUsageRoom1()
        == other.getElecUsageRoom1());
    result = result && (getElecUsageRoom2()
        == other.getElecUsageRoom2());
    result = result && (getElecUsageRoom3()
        == other.getElecUsageRoom3());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ELEC_USAGE_ROOM1_FIELD_NUMBER;
    hash = (53 * hash) + getElecUsageRoom1();
    hash = (37 * hash) + ELEC_USAGE_ROOM2_FIELD_NUMBER;
    hash = (53 * hash) + getElecUsageRoom2();
    hash = (37 * hash) + ELEC_USAGE_ROOM3_FIELD_NUMBER;
    hash = (53 * hash) + getElecUsageRoom3();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.foresightMaintenance.CheckElecUsageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foresightMaintenance.CheckElecUsageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckElecUsageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foresightMaintenance.CheckElecUsageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckElecUsageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foresightMaintenance.CheckElecUsageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckElecUsageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foresightMaintenance.CheckElecUsageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckElecUsageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.foresightMaintenance.CheckElecUsageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foresightMaintenance.CheckElecUsageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foresightMaintenance.CheckElecUsageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.foresightMaintenance.CheckElecUsageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *message response for CheckElecUsage
   * </pre>
   *
   * Protobuf type {@code foresightMaintenance.CheckElecUsageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:foresightMaintenance.CheckElecUsageResponse)
      grpc.foresightMaintenance.CheckElecUsageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckElecUsageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckElecUsageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.foresightMaintenance.CheckElecUsageResponse.class, grpc.foresightMaintenance.CheckElecUsageResponse.Builder.class);
    }

    // Construct using grpc.foresightMaintenance.CheckElecUsageResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      elecUsageRoom1_ = 0;

      elecUsageRoom2_ = 0;

      elecUsageRoom3_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.foresightMaintenance.foresightMaintenanceImpl.internal_static_foresightMaintenance_CheckElecUsageResponse_descriptor;
    }

    @java.lang.Override
    public grpc.foresightMaintenance.CheckElecUsageResponse getDefaultInstanceForType() {
      return grpc.foresightMaintenance.CheckElecUsageResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.foresightMaintenance.CheckElecUsageResponse build() {
      grpc.foresightMaintenance.CheckElecUsageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.foresightMaintenance.CheckElecUsageResponse buildPartial() {
      grpc.foresightMaintenance.CheckElecUsageResponse result = new grpc.foresightMaintenance.CheckElecUsageResponse(this);
      result.elecUsageRoom1_ = elecUsageRoom1_;
      result.elecUsageRoom2_ = elecUsageRoom2_;
      result.elecUsageRoom3_ = elecUsageRoom3_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.foresightMaintenance.CheckElecUsageResponse) {
        return mergeFrom((grpc.foresightMaintenance.CheckElecUsageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.foresightMaintenance.CheckElecUsageResponse other) {
      if (other == grpc.foresightMaintenance.CheckElecUsageResponse.getDefaultInstance()) return this;
      if (other.getElecUsageRoom1() != 0) {
        setElecUsageRoom1(other.getElecUsageRoom1());
      }
      if (other.getElecUsageRoom2() != 0) {
        setElecUsageRoom2(other.getElecUsageRoom2());
      }
      if (other.getElecUsageRoom3() != 0) {
        setElecUsageRoom3(other.getElecUsageRoom3());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.foresightMaintenance.CheckElecUsageResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.foresightMaintenance.CheckElecUsageResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int elecUsageRoom1_ ;
    /**
     * <code>int32 elec_usage_room1 = 1;</code>
     */
    public int getElecUsageRoom1() {
      return elecUsageRoom1_;
    }
    /**
     * <code>int32 elec_usage_room1 = 1;</code>
     */
    public Builder setElecUsageRoom1(int value) {
      
      elecUsageRoom1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 elec_usage_room1 = 1;</code>
     */
    public Builder clearElecUsageRoom1() {
      
      elecUsageRoom1_ = 0;
      onChanged();
      return this;
    }

    private int elecUsageRoom2_ ;
    /**
     * <code>int32 elec_usage_room2 = 2;</code>
     */
    public int getElecUsageRoom2() {
      return elecUsageRoom2_;
    }
    /**
     * <code>int32 elec_usage_room2 = 2;</code>
     */
    public Builder setElecUsageRoom2(int value) {
      
      elecUsageRoom2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 elec_usage_room2 = 2;</code>
     */
    public Builder clearElecUsageRoom2() {
      
      elecUsageRoom2_ = 0;
      onChanged();
      return this;
    }

    private int elecUsageRoom3_ ;
    /**
     * <code>int32 elec_usage_room3 = 3;</code>
     */
    public int getElecUsageRoom3() {
      return elecUsageRoom3_;
    }
    /**
     * <code>int32 elec_usage_room3 = 3;</code>
     */
    public Builder setElecUsageRoom3(int value) {
      
      elecUsageRoom3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 elec_usage_room3 = 3;</code>
     */
    public Builder clearElecUsageRoom3() {
      
      elecUsageRoom3_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:foresightMaintenance.CheckElecUsageResponse)
  }

  // @@protoc_insertion_point(class_scope:foresightMaintenance.CheckElecUsageResponse)
  private static final grpc.foresightMaintenance.CheckElecUsageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.foresightMaintenance.CheckElecUsageResponse();
  }

  public static grpc.foresightMaintenance.CheckElecUsageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckElecUsageResponse>
      PARSER = new com.google.protobuf.AbstractParser<CheckElecUsageResponse>() {
    @java.lang.Override
    public CheckElecUsageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CheckElecUsageResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CheckElecUsageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckElecUsageResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.foresightMaintenance.CheckElecUsageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

