// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foresightMaintenance.proto

package grpc.foresightMaintenance;

public interface CheckCo2LevelsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foresightMaintenance.CheckCo2LevelsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 co2level_room1 = 1;</code>
   */
  int getCo2LevelRoom1();

  /**
   * <code>int32 co2level_room2 = 2;</code>
   */
  int getCo2LevelRoom2();

  /**
   * <code>int32 co2level_room3 = 3;</code>
   */
  int getCo2LevelRoom3();
}
