// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foresightMaintenance.proto

package grpc.foresightMaintenance;

public final class foresightMaintenanceImpl {
  private foresightMaintenanceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foresightMaintenance_CheckCo2LevelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foresightMaintenance_CheckCo2LevelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foresightMaintenance_CheckCo2LevelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foresightMaintenance_CheckCo2LevelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foresightMaintenance_CheckElecUsageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foresightMaintenance_CheckElecUsageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foresightMaintenance_CheckElecUsageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foresightMaintenance_CheckElecUsageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foresightMaintenance_CheckDecibelLevelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foresightMaintenance_CheckDecibelLevelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foresightMaintenance_CheckDecibelLevelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foresightMaintenance_CheckDecibelLevelsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032foresightMaintenance.proto\022\024foresightM" +
      "aintenance\"_\n\025CheckCo2LevelsRequest\022\026\n\016c" +
      "o2level_room1\030\001 \001(\005\022\026\n\016co2level_room2\030\002 " +
      "\001(\005\022\026\n\016co2level_room3\030\003 \001(\005\"`\n\026CheckCo2L" +
      "evelsResponse\022\026\n\016co2level_room1\030\001 \001(\005\022\026\n" +
      "\016co2level_room2\030\002 \001(\005\022\026\n\016co2level_room3\030" +
      "\003 \001(\005\"e\n\025CheckElecUsageRequest\022\030\n\020elec_u" +
      "sage_room1\030\001 \001(\005\022\030\n\020elec_usage_room2\030\002 \001" +
      "(\005\022\030\n\020elec_usage_room3\030\003 \001(\005\"f\n\026CheckEle" +
      "cUsageResponse\022\030\n\020elec_usage_room1\030\001 \001(\005" +
      "\022\030\n\020elec_usage_room2\030\002 \001(\005\022\030\n\020elec_usage" +
      "_room3\030\003 \001(\005\"`\n\031CheckDecibelLevelsReques" +
      "t\022\025\n\rdecibel_room1\030\001 \001(\005\022\025\n\rdecibel_room" +
      "2\030\002 \001(\005\022\025\n\rdecibel_room3\030\003 \001(\005\"a\n\032CheckD" +
      "ecibelLevelsResponse\022\025\n\rdecibel_room1\030\001 " +
      "\001(\005\022\025\n\rdecibel_room2\030\002 \001(\005\022\025\n\rdecibel_ro" +
      "om3\030\003 \001(\0052\373\002\n\024foresightMaintenance\022q\n\016Ch" +
      "eckCo2Levels\022+.foresightMaintenance.Chec" +
      "kCo2LevelsRequest\032,.foresightMaintenance" +
      ".CheckCo2LevelsResponse\"\000(\0010\001\022q\n\016CheckEl" +
      "ecUsage\022+.foresightMaintenance.CheckElec" +
      "UsageRequest\032,.foresightMaintenance.Chec" +
      "kElecUsageResponse\"\000(\0010\001\022}\n\022CheckDecibel" +
      "Levels\022/.foresightMaintenance.CheckDecib" +
      "elLevelsRequest\0320.foresightMaintenance.C" +
      "heckDecibelLevelsResponse\"\000(\0010\001B7\n\031grpc." +
      "foresightMaintenanceB\030foresightMaintenan" +
      "ceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_foresightMaintenance_CheckCo2LevelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_foresightMaintenance_CheckCo2LevelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foresightMaintenance_CheckCo2LevelsRequest_descriptor,
        new java.lang.String[] { "Co2LevelRoom1", "Co2LevelRoom2", "Co2LevelRoom3", });
    internal_static_foresightMaintenance_CheckCo2LevelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_foresightMaintenance_CheckCo2LevelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foresightMaintenance_CheckCo2LevelsResponse_descriptor,
        new java.lang.String[] { "Co2LevelRoom1", "Co2LevelRoom2", "Co2LevelRoom3", });
    internal_static_foresightMaintenance_CheckElecUsageRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_foresightMaintenance_CheckElecUsageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foresightMaintenance_CheckElecUsageRequest_descriptor,
        new java.lang.String[] { "ElecUsageRoom1", "ElecUsageRoom2", "ElecUsageRoom3", });
    internal_static_foresightMaintenance_CheckElecUsageResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_foresightMaintenance_CheckElecUsageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foresightMaintenance_CheckElecUsageResponse_descriptor,
        new java.lang.String[] { "ElecUsageRoom1", "ElecUsageRoom2", "ElecUsageRoom3", });
    internal_static_foresightMaintenance_CheckDecibelLevelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_foresightMaintenance_CheckDecibelLevelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foresightMaintenance_CheckDecibelLevelsRequest_descriptor,
        new java.lang.String[] { "DecibelRoom1", "DecibelRoom2", "DecibelRoom3", });
    internal_static_foresightMaintenance_CheckDecibelLevelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_foresightMaintenance_CheckDecibelLevelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foresightMaintenance_CheckDecibelLevelsResponse_descriptor,
        new java.lang.String[] { "DecibelRoom1", "DecibelRoom2", "DecibelRoom3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
