// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newEnergyEfficiency.proto

package grpc.newEnergyEfficiency;

public final class NewnEnergyEfficiencyImpl {
  private NewnEnergyEfficiencyImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031newEnergyEfficiency.proto\"%\n\016containsS" +
      "tring\022\023\n\013firstString\030\001 \001(\t2\254\001\n\023newEnergy" +
      "Efficiency\0221\n\013GetPresRoom\022\017.containsStri" +
      "ng\032\017.containsString\"\000\0221\n\tGetLights\022\017.con" +
      "tainsString\032\017.containsString\"\0000\001\022/\n\007GetH" +
      "eat\022\017.containsString\032\017.containsString\"\0000" +
      "\001B6\n\030grpc.newEnergyEfficiencyB\030NewnEnerg" +
      "yEfficiencyImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_containsString_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_containsString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsString_descriptor,
        new java.lang.String[] { "FirstString", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
