// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newEnergyEfficiency.proto

package grpc.newEnergyEfficiency;

public interface responseLightsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:responseLights)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 firstInt = 1;</code>
   */
  int getFirstInt();
}
